{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "devdata",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/devdata",
    "uid": "6ec2ea00-9f19-4fe4-8b97-f5ce0e82015d",
    "resourceVersion": "196352",
    "generation": 2,
    "creationTimestamp": "2020-04-15T05:07:51Z",
    "labels": {
      "k8s-app": "devdata"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "2"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "k8s-app": "devdata"
      }
    },
    "template": {
      "metadata": {
        "name": "devdata",
        "creationTimestamp": null,
        "labels": {
          "k8s-app": "devdata"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "devdata",
            "image": "adarshalunia/mysql_db",
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always",
            "securityContext": {
              "privileged": false
            }
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "imagePullSecrets": [
          {
            "name": "regcred"
          }
        ],
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 2,
    "replicas": 1,
    "updatedReplicas": 1,
    "unavailableReplicas": 1,
    "conditions": [
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2020-04-15T05:10:22Z",
        "lastTransitionTime": "2020-04-15T05:07:51Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"devdata-dc9d74459\" has successfully progressed."
      },
      {
        "type": "Available",
        "status": "False",
        "lastUpdateTime": "2020-04-15T05:10:23Z",
        "lastTransitionTime": "2020-04-15T05:10:23Z",
        "reason": "MinimumReplicasUnavailable",
        "message": "Deployment does not have minimum availability."
      }
    ]
  }
}