apiVersion: apps/v1
kind: Deployment
metadata:
  name: training_201
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  training_201
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: training_201
    spec:
      containers:
      - name: training_201
        resources:
          limits:
            memory: 1024Mi
            cpu: 300m
          requests:
            memory: 400Mi
            cpu: 50m
        image: dhdevregistrypoc.azurecr.io/training_201_img:BUILD_ID
        ports:
        - containerPort: 9001

--- 
{
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "training_201"
      },
      "spec": {
        "ports": [{
          "port": 80,
          "targetPort": 9001
        }],
        "selector": {
          "app": "training_201"
        }
      }
    }

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: training_201
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: training_201
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 75
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
