version: "1"

services:
   db:
     image: mysql_db
     ports:
      - 3306:3306 
     environment :
      MYSQL_ROOT_PASSWORD:mysql
     volume:
      - my-datavolume:/var/lib/mysql
       
   UI:
    image: traning_app
    ports:
     - 8080:8080
    depends_on:
    - db

   
volumes:
  my-datavolume:
      
    