version: '2'

services:
   db:
     image: adarshalunia/mysql_db
     container_name: mysql_db
     ports:
      - 3306:3306 
     environment :
      MYSQL_ROOT_PASSWORD: mysql
     volumes:
      - my-datavolume:/var/lib/mysql
       
   UI:
    image: adarshalunia/training_app
    ports:
     - 8080:8080
    depends_on:
    - db

   
volumes:
  my-datavolume:
      
    
